##### Numpy'ı Dahil Edin

In [1]:
import numpy as np

##### 5 tane 1 barındıran bir array oluşturun

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# Bu satırı çalıştırmayın

array([1., 1., 1., 1., 1.])

##### 5 tane 0 barındıran bir array oluşturun

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# Bu satırı çalıştırmayın

array([0., 0., 0., 0., 0.])

##### 2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [4]:
np.arange(2,102,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [7]:
# Bu satırı çalıştırmayın

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

##### 5 tane 10 bulunan bir array oluşturun

In [5]:
np.ones(5) * 10

array([10., 10., 10., 10., 10.])

In [10]:
# Bu satırı çalıştırmayın

array([10., 10., 10., 10., 10.])

##### 1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [6]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
# Bu satırı çalıştırmayın

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### 4x4'lük bir birim matris oluşturun

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Bu satırı çalıştırmayın

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### 0 ile 5 arasında rastgele değerler üretin

In [10]:
np.random.rand()*5

4.753809886172891

In [20]:
# Bu satırı çalıştırmayın

4.5693236808831825

##### 5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [35]:
np.random.randn(25).reshape(5,5)

array([[-1.05582388, -0.74942157, -0.68364528,  1.50309011, -1.33375795],
       [-0.2116169 ,  1.2757176 , -1.8058825 , -2.06479931,  0.751363  ],
       [-0.10816524, -1.00921582,  0.51374161, -1.22190525,  0.41788539],
       [-2.09075852,  0.57676219, -0.43892559,  0.58999209, -0.66927036],
       [-0.13076098,  0.28404001, -0.42057808, -1.86174214, -0.01111389]])

In [36]:
# Bu satırı çalıştırmayın

##### 1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [13]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [23]:
# Bu satırı çalıştırmayın

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

### Array Indekslenmesi

In [15]:
arr  = np.arange(1,101).reshape(10,10)

In [16]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

##### Indeks işlemlerini kullanarak aşağıdaki sonuçları elde etmeye çalışın

In [17]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [85]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [31]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [19]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [34]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [20]:
arr[:3,1]

array([ 2, 12, 22])

In [36]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 2, 12, 22])

In [21]:
arr[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [37]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 2],
       [12],
       [22]])

In [22]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [38]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### Array Operasyonları

Not: Arrayler rastgele sayılarla çalıştırıldığı için sizde çıkan sonuçlar buradakilerle aynı olmayacaktır.

In [23]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [24]:
arr1

array([[1, 4, 2],
       [0, 4, 3],
       [4, 1, 0]])

In [25]:
arr2

array([[4, 0, 3],
       [4, 0, 4],
       [0, 4, 1]])

##### İki Matrisi Toplayın

In [26]:
arr1+arr2

array([[5, 4, 5],
       [4, 4, 7],
       [4, 5, 1]])

##### İki Matrisi Çarpın

In [27]:
arr1*arr2

array([[ 4,  0,  6],
       [ 0,  0, 12],
       [ 0,  4,  0]])

##### arr1 matrisinin tüm elemanlarının ortalamasını bulun

In [28]:
arr1.mean()

2.111111111111111

##### arr1 matrisinin tüm elemanlarının toplamını bulun

In [29]:
arr1.sum()

19