# Numpy

In [1]:
liste=[1,2,3]

In [2]:
liste

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
nListe= np.array(liste)

In [5]:
nListe

array([1, 2, 3])

In [6]:
nListe[0]

1

In [7]:
nListe2=np.array([1,2,3])

In [8]:
nListe2

array([1, 2, 3])

In [9]:
liste2=[[10,20,30],[40,50,60],[70,80,90]]

In [10]:
nListe3=np.array(liste2)

In [11]:
nListe3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
liste2

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [13]:
nListe3[2,2]

90

In [14]:
nListe4=nListe3

In [15]:
nListe4

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
nListe3[2,2]=0

In [17]:
nListe3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80,  0]])

In [18]:
nListe4

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80,  0]])

In [19]:
nListe5=nListe3.copy()

In [20]:
nListe5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80,  0]])

In [21]:
nListe3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80,  0]])

In [22]:
nListe3[2,2]=90

In [23]:
nListe3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [24]:
nListe4

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
nListe5

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80,  0]])

In [26]:
nListe6=np.arange(10,20)

In [27]:
nListe6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [35]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.randint(0,10)

9

In [38]:
np.random.randint(0,10)

1

In [39]:
np.random.randint(1,10,5)

array([3, 4, 8, 1, 9])

In [40]:
np.random.rand(5)

array([0.92304956, 0.08609139, 0.49588016, 0.7956512 , 0.61023173])

In [43]:
nListe7=np.random.randint(1,100,25)

In [44]:
nListe7

array([64, 99, 51, 15, 95, 88, 46, 23, 24, 87, 68, 84, 11, 15, 29, 34, 80,
       45, 99, 77, 38, 60, 72, 55, 97])

In [46]:
nListe7.reshape(5,5)

array([[64, 99, 51, 15, 95],
       [88, 46, 23, 24, 87],
       [68, 84, 11, 15, 29],
       [34, 80, 45, 99, 77],
       [38, 60, 72, 55, 97]])

In [47]:
nListe7

array([64, 99, 51, 15, 95, 88, 46, 23, 24, 87, 68, 84, 11, 15, 29, 34, 80,
       45, 99, 77, 38, 60, 72, 55, 97])

In [48]:
nListe7.max()

99

In [49]:
nListe7.min()

11

In [50]:
nListe7.sum()

1456

In [51]:
nListe7.mean()

58.24

In [52]:
nListe7.argmin()

12

In [53]:
nListe7.argmax()

1

In [54]:
nListe7[1:5]

array([99, 51, 15, 95])

In [55]:
nListe7[1:]

array([99, 51, 15, 95, 88, 46, 23, 24, 87, 68, 84, 11, 15, 29, 34, 80, 45,
       99, 77, 38, 60, 72, 55, 97])

In [56]:
nListe7[:5]

array([64, 99, 51, 15, 95])

In [57]:
nListe7[::2]

array([64, 51, 95, 46, 24, 68, 11, 29, 80, 99, 38, 72, 97])

In [58]:
nListe7<50

array([False, False, False,  True, False, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True, False,  True,
       False, False,  True, False, False, False, False])

In [59]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([1,2,3,4,5,])

In [60]:
arr1+arr2

array([11, 22, 33, 44, 55])

In [61]:
arr1*arr2

array([ 10,  40,  90, 160, 250])

In [62]:
arr1-arr2

array([ 9, 18, 27, 36, 45])

In [63]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [64]:
arr2**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [65]:
narray=np.array([1,2,3,4,5,6,7,8,9])

In [66]:
np.sin(narray)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [67]:
np.cos(narray)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [68]:
np.sqrt(narray)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [69]:
np.log(narray)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [70]:
narray.var()

6.666666666666667

In [71]:
narray.std()

2.581988897471611

In [72]:
np.median(narray)

5.0

In [73]:
narray2=np.array([9,8,7,6,5,4,3,2,1])

In [74]:
np.add(narray,narray2)

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
np.subract(narray,narray2)