##### Numpy'ı Dahil Edin

##### 5 tane 1 barındıran bir array oluşturun

In [5]:
# Bu satırı çalıştırmayın

array([1., 1., 1., 1., 1.])

##### 5 tane 0 barındıran bir array oluşturun

In [6]:
# Bu satırı çalıştırmayın

array([0., 0., 0., 0., 0.])

##### 2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [7]:
# Bu satırı çalıştırmayın

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

##### 5 tane 10 bulunan bir array oluşturun

In [10]:
# Bu satırı çalıştırmayın

array([10., 10., 10., 10., 10.])

##### 1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [11]:
# Bu satırı çalıştırmayın

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### 4x4'lük bir birim matris oluşturun

In [12]:
# Bu satırı çalıştırmayın

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### 0 ile 5 arasında rastgele değerler üretin

In [20]:
# Bu satırı çalıştırmayın

4.5693236808831825

##### 5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [21]:
# Bu satırı çalıştırmayın

array([[-1.05647946,  0.88447651, -0.09589524,  0.707474  , -1.27075888],
       [ 1.98577112,  2.11969776, -0.62400642,  0.69932275,  0.11141592],
       [-0.71398274,  0.85916974,  0.51843923,  2.31872337,  0.48762873],
       [-1.18549889,  0.30847846,  1.0822357 ,  1.43461576, -0.10142078],
       [-0.15602908,  0.30583364,  1.69070191,  0.06727983, -0.17285088]])

##### 1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [23]:
# Bu satırı çalıştırmayın

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

### Array Indekslenmesi

In [83]:
arr  = np.arange(1,101).reshape(10,10)

In [84]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

##### Indeks işlemlerini kullanarak aşağıdaki sonuçları elde etmeye çalışın

In [85]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [34]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [36]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 2, 12, 22])

In [37]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 2],
       [12],
       [22]])

In [38]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### Array Operasyonları

Not: Arrayler rastgele sayılarla çalıştırıldığı için sizde çıkan sonuçlar buradakilerle aynı olmayacaktır.

In [65]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [66]:
arr1

array([[3, 0, 2],
       [3, 4, 2],
       [3, 0, 4]])

In [67]:
arr2

array([[3, 4, 3],
       [3, 3, 3],
       [3, 1, 2]])

##### İki Matrisi Toplayın

array([[6, 4, 5],
       [6, 7, 5],
       [6, 1, 6]])

##### İki Matrisi Çarpın

array([[ 9,  0,  6],
       [ 9, 12,  6],
       [ 9,  0,  8]])

##### arr1 matrisinin tüm elemanlarının ortalamasını bulun

2.3333333333333335

##### arr1 matrisinin tüm elemanlarının toplamını bulun

21