# Pandas Serileri

In [1]:
import numpy as np
import pandas as pd

In [2]:
liste1=["a","b","c","d","e"]

In [3]:
liste2=[1,2,3,4,5]

In [5]:
pd.Series(data=liste2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
pd.Series(data=liste2, index=liste1)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
npArray= np.array([10,20,30,40,50])

In [8]:
npArray

array([10, 20, 30, 40, 50])

In [11]:
pd.Series(data=npArray,index=["a","b","c","d","e"])

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [12]:
sozluk={"a":30,"b":40,"c":70}

In [13]:
pd.Series(sozluk)

a    30
b    40
c    70
dtype: int64

In [14]:
ser1=pd.Series([1,2,3,4,5],["a","b","c","d","e"])

In [15]:
ser2=pd.Series([7,5,6,9,8],["a","b","c","f","e"])

In [16]:
ser1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
ser2

a    7
b    5
c    6
f    9
e    8
dtype: int64

In [18]:
ser1["a"]

1

In [19]:
ser1+ser2

a     8.0
b     7.0
c     9.0
d     NaN
e    13.0
f     NaN
dtype: float64

In [20]:
top=ser1+ser2

In [21]:
top

a     8.0
b     7.0
c     9.0
d     NaN
e    13.0
f     NaN
dtype: float64

In [24]:
top["d"]

nan

In [25]:
top["g"]

KeyError: 'g'

# Dataframe

In [26]:
from numpy.random import randn

In [27]:
randn(3,3)

array([[-1.70004067, -2.94217545, -1.08732693],
       [ 1.98033061, -0.96353826,  0.04472282],
       [-0.97920031, -0.72384787, -0.04062348]])

In [28]:
df=pd.DataFrame(randn(3,3), index=["A","B","C"], columns=["C1","C2","C3"])

In [29]:
df

C1        C2        C3
A -1.036711 -0.567094  0.269684
B -2.565650 -1.929377  0.912925
C  0.255604 -0.388865 -1.186811

In [30]:
df["C1"]

A   -1.036711
B   -2.565650
C    0.255604
Name: C1, dtype: float64

In [31]:
type(df["C1"])

pandas.core.series.Series

In [32]:
df.loc["A"]

C1   -1.036711
C2   -0.567094
C3    0.269684
Name: A, dtype: float64

In [33]:
type(df.loc["A"])

pandas.core.series.Series

In [36]:
df[["C1","C2"]]

C1        C2
A -1.036711 -0.567094
B -2.565650 -1.929377
C  0.255604 -0.388865

In [37]:
df["C4"]

KeyError: 'C4'

In [38]:
df["C4"]=pd.Series(randn(3),index=["A","B","C"])

In [39]:
df

C1        C2        C3        C4
A -1.036711 -0.567094  0.269684  0.083236
B -2.565650 -1.929377  0.912925 -0.051316
C  0.255604 -0.388865 -1.186811 -0.709679

In [40]:
df["C5"]=df["C1"]+df["C2"]+df["C3"]+df["C4"]

In [41]:
df

C1        C2        C3        C4        C5
A -1.036711 -0.567094  0.269684  0.083236 -1.250885
B -2.565650 -1.929377  0.912925 -0.051316 -3.633418
C  0.255604 -0.388865 -1.186811 -0.709679 -2.029750

In [43]:
df.drop("C5",axis=1)

C1        C2        C3        C4
A -1.036711 -0.567094  0.269684  0.083236
B -2.565650 -1.929377  0.912925 -0.051316
C  0.255604 -0.388865 -1.186811 -0.709679

In [44]:
df

C1        C2        C3        C4        C5
A -1.036711 -0.567094  0.269684  0.083236 -1.250885
B -2.565650 -1.929377  0.912925 -0.051316 -3.633418
C  0.255604 -0.388865 -1.186811 -0.709679 -2.029750

In [45]:
df.drop("C5",axis=1,inplace=True)

In [46]:
df

C1        C2        C3        C4
A -1.036711 -0.567094  0.269684  0.083236
B -2.565650 -1.929377  0.912925 -0.051316
C  0.255604 -0.388865 -1.186811 -0.709679

# Koşullar

In [47]:
df > -1

C1     C2     C3    C4
A  False   True   True  True
B  False  False   True  True
C   True   True  False  True

In [48]:
boolDf=df > -1

In [49]:
boolDf

C1     C2     C3    C4
A  False   True   True  True
B  False  False   True  True
C   True   True  False  True

In [50]:
df[boolDf]

C1        C2        C3        C4
A       NaN -0.567094  0.269684  0.083236
B       NaN       NaN  0.912925 -0.051316
C  0.255604 -0.388865       NaN -0.709679

In [51]:
df[df<-1]

C1        C2        C3  C4
A -1.036711       NaN       NaN NaN
B -2.565650 -1.929377       NaN NaN
C       NaN       NaN -1.186811 NaN

In [52]:
df["C1"]<-1

A     True
B     True
C    False
Name: C1, dtype: bool

In [53]:
df

C1        C2        C3        C4
A -1.036711 -0.567094  0.269684  0.083236
B -2.565650 -1.929377  0.912925 -0.051316
C  0.255604 -0.388865 -1.186811 -0.709679

In [55]:
df[(df["C1"]<-1) & (df["C3"]>0)]

C1        C2        C3        C4
A -1.036711 -0.567094  0.269684  0.083236
B -2.565650 -1.929377  0.912925 -0.051316

In [59]:
df[(df["C1"]<0) | (df["C4"]>-1)]

C1        C2        C3        C4
A -1.036711 -0.567094  0.269684  0.083236
B -2.565650 -1.929377  0.912925 -0.051316
C  0.255604 -0.388865 -1.186811 -0.709679

In [60]:
df["C5"]=["new1","new2","new3"]

In [61]:
df

C1        C2        C3        C4    C5
A -1.036711 -0.567094  0.269684  0.083236  new1
B -2.565650 -1.929377  0.912925 -0.051316  new2
C  0.255604 -0.388865 -1.186811 -0.709679  new3

In [62]:
df.set_index("C5")

C1        C2        C3        C4
C5                                          
new1 -1.036711 -0.567094  0.269684  0.083236
new2 -2.565650 -1.929377  0.912925 -0.051316
new3  0.255604 -0.388865 -1.186811 -0.709679

In [63]:
df

C1        C2        C3        C4    C5
A -1.036711 -0.567094  0.269684  0.083236  new1
B -2.565650 -1.929377  0.912925 -0.051316  new2
C  0.255604 -0.388865 -1.186811 -0.709679  new3

In [64]:
df.set_index("C5",inplace=True)

In [65]:
df

C1        C2        C3        C4
C5                                          
new1 -1.036711 -0.567094  0.269684  0.083236
new2 -2.565650 -1.929377  0.912925 -0.051316
new3  0.255604 -0.388865 -1.186811 -0.709679

In [66]:
df.index.names

FrozenList(['C5'])

In [67]:
outerIndex=["Group1","Group1","Group1","Group2","Group2","Group2","Group3","Group3","Group3"]

In [68]:
innerIndex=["Index1","Index2","Index3","Index1","Index2","Index3","Index1","Index2","Index3"]

In [69]:
list(zip(outerIndex,innerIndex))

[('Group1', 'Index1'),
 ('Group1', 'Index2'),
 ('Group1', 'Index3'),
 ('Group2', 'Index1'),
 ('Group2', 'Index2'),
 ('Group2', 'Index3'),
 ('Group3', 'Index1'),
 ('Group3', 'Index2'),
 ('Group3', 'Index3')]

In [70]:
hierarchy=list(zip(outerIndex,innerIndex))

In [71]:
hierarchy

[('Group1', 'Index1'),
 ('Group1', 'Index2'),
 ('Group1', 'Index3'),
 ('Group2', 'Index1'),
 ('Group2', 'Index2'),
 ('Group2', 'Index3'),
 ('Group3', 'Index1'),
 ('Group3', 'Index2'),
 ('Group3', 'Index3')]

In [72]:
hierarchy=pd.MultiIndex.from_tuples(hierarchy)

In [73]:
hierarchy

MultiIndex([('Group1', 'Index1'),
            ('Group1', 'Index2'),
            ('Group1', 'Index3'),
            ('Group2', 'Index1'),
            ('Group2', 'Index2'),
            ('Group2', 'Index3'),
            ('Group3', 'Index1'),
            ('Group3', 'Index2'),
            ('Group3', 'Index3')],
           )

In [74]:
df2=pd.DataFrame(randn(9,3),hierarchy,columns=["A","B","C"])

In [75]:
df2

A         B         C
Group1 Index1  0.445464  1.262286 -0.251293
       Index2  0.889961  0.113919 -0.006761
       Index3  2.550427  0.740515 -1.508224
Group2 Index1 -0.934540 -0.068797  2.071529
       Index2  0.364054  0.405616 -1.545774
       Index3 -0.550499  0.933396  0.005274
Group3 Index1 -1.022763 -0.460297  0.011128
       Index2  1.002057  1.046596 -0.907648
       Index3 -1.018016  0.155241 -2.277348

In [77]:
df2["A"]

Group1  Index1    0.445464
        Index2    0.889961
        Index3    2.550427
Group2  Index1   -0.934540
        Index2    0.364054
        Index3   -0.550499
Group3  Index1   -1.022763
        Index2    1.002057
        Index3   -1.018016
Name: A, dtype: float64

In [79]:
df2.loc["Group1"]

A         B         C
Index1  0.445464  1.262286 -0.251293
Index2  0.889961  0.113919 -0.006761
Index3  2.550427  0.740515 -1.508224

In [80]:
df2.loc[["Group1","Group2"]]

A         B         C
Group1 Index1  0.445464  1.262286 -0.251293
       Index2  0.889961  0.113919 -0.006761
       Index3  2.550427  0.740515 -1.508224
Group2 Index1 -0.934540 -0.068797  2.071529
       Index2  0.364054  0.405616 -1.545774
       Index3 -0.550499  0.933396  0.005274

In [81]:
df2.loc["Group1"].loc["Index1"]

A    0.445464
B    1.262286
C   -0.251293
Name: Index1, dtype: float64

In [83]:
df2.index.names

FrozenList([None, None])

In [84]:
df2.index.names=["Groups","Indexes"]

In [85]:
df2

A         B         C
Groups Indexes                              
Group1 Index1   0.445464  1.262286 -0.251293
       Index2   0.889961  0.113919 -0.006761
       Index3   2.550427  0.740515 -1.508224
Group2 Index1  -0.934540 -0.068797  2.071529
       Index2   0.364054  0.405616 -1.545774
       Index3  -0.550499  0.933396  0.005274
Group3 Index1  -1.022763 -0.460297  0.011128
       Index2   1.002057  1.046596 -0.907648
       Index3  -1.018016  0.155241 -2.277348

In [86]:
df2.loc["Group1"].loc["Index1"]["A"]

0.44546409391047964

In [87]:
df2.xs("Group1")

A         B         C
Indexes                              
Index1   0.445464  1.262286 -0.251293
Index2   0.889961  0.113919 -0.006761
Index3   2.550427  0.740515 -1.508224

In [88]:
df2.xs("Group1").xs("Index1")

A    0.445464
B    1.262286
C   -0.251293
Name: Index1, dtype: float64

In [89]:
df2.xs("Group1").xs("Index1").xs("A")

0.44546409391047964

# Kayıp Veriler

In [90]:
arr=np.array([[10,20,np.nan],[5,np.nan,np.nan],[23,np.nan,14]])

In [91]:
arr

array([[10., 20., nan],
       [ 5., nan, nan],
       [23., nan, 14.]])

In [92]:
df=pd.DataFrame(arr,index=["i1","i2","i3"],columns=["c1","c2","c3"])

In [93]:
df

c1    c2    c3
i1  10.0  20.0   NaN
i2   5.0   NaN   NaN
i3  23.0   NaN  14.0

In [94]:
df.dropna()

Empty DataFrame
Columns: [c1, c2, c3]
Index: []

In [95]:
df

c1    c2    c3
i1  10.0  20.0   NaN
i2   5.0   NaN   NaN
i3  23.0   NaN  14.0

In [96]:
df.dropna(axis=1)

c1
i1  10.0
i2   5.0
i3  23.0

In [100]:
df.dropna(thresh=2)

c1    c2    c3
i1  10.0  20.0   NaN
i3  23.0   NaN  14.0

In [98]:
df.fillna(value=1)

c1    c2    c3
i1  10.0  20.0   1.0
i2   5.0   1.0   1.0
i3  23.0   1.0  14.0

## NaN değerlerini değerlerin ortalaması ile değiştirmek

In [101]:
df.sum()

c1    38.0
c2    20.0
c3    14.0
dtype: float64

In [102]:
df.sum().sum()

72.0

In [103]:
df.size

9

In [104]:
df.isnull().sum().sum()

4

In [105]:
def calculateMean(df):
    totalSum=df.sum().sum()
    totalNum=df.size-df.isnull().sum().sum()
    return totalSum/totalNum
df.fillna(value=calculateMean(df))

c1    c2    c3
i1  10.0  20.0  14.4
i2   5.0  14.4  14.4
i3  23.0  14.4  14.0

# GroupBy Sorguları

In [106]:
dataset = {
        "Departman":["Bilişim","İnsan Kaynakları","Üretim","Üretim","Bilişim","İnsan Kaynakları"],
        "Çalışan": ["Mustafa","Jale","Kadir","Zeynep","Murat","Ahmet"],
        "Maaş":[3000,3500,2500,4500,4000,2000]
        }

In [107]:
dataset

{'Departman': ['Bilişim',
  'İnsan Kaynakları',
  'Üretim',
  'Üretim',
  'Bilişim',
  'İnsan Kaynakları'],
 'Çalışan': ['Mustafa', 'Jale', 'Kadir', 'Zeynep', 'Murat', 'Ahmet'],
 'Maaş': [3000, 3500, 2500, 4500, 4000, 2000]}

In [108]:
df=pd.DataFrame(dataset)

In [109]:
df

Departman  Çalışan  Maaş
0           Bilişim  Mustafa  3000
1  İnsan Kaynakları     Jale  3500
2            Üretim    Kadir  2500
3            Üretim   Zeynep  4500
4           Bilişim    Murat  4000
5  İnsan Kaynakları    Ahmet  2000

In [110]:
depGroup=df.groupby("Departman")

In [111]:
depGroup

In [112]:
depGroup.sum()

Maaş
Departman             
Bilişim           7000
Üretim            7000
İnsan Kaynakları  5500

In [114]:
df.groupby("Departman").count()

Çalışan  Maaş
Departman                      
Bilişim                 2     2
Üretim                  2     2
İnsan Kaynakları        2     2

In [115]:
df.groupby("Departman").min()["Maaş"]["Bilişim"]

3000

In [116]:
df.groupby("Departman").mean().loc["Bilişim"]["Maaş"]

3500

# Merge, Join ve Concate

## Concate

In [117]:
dataset1 = {
    "A": ["A1","A2","A3","A4"],
    "B":["B1","B2","B3","B4"],
    "C":["C1","C2","C3","C4"],
}
dataset2 = {
    "A": ["A5","A6","A7","A8"],
    "B":["B5","B6","B7","B8"],
    "C":["C5","C6","C7","C8"],
}

In [118]:
df1=pd.DataFrame(dataset1,index=[1,2,3,4])
df2=pd.DataFrame(dataset2,index=[5,6,7,8])

In [119]:
df1

A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4

In [120]:
df2

A   B   C
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7
8  A8  B8  C8

In [123]:
pd.concat([df1,df2])

A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7
8  A8  B8  C8

In [124]:
pd.concat([df1,df2],axis=1)

A    B    C    A    B    C
1   A1   B1   C1  NaN  NaN  NaN
2   A2   B2   C2  NaN  NaN  NaN
3   A3   B3   C3  NaN  NaN  NaN
4   A4   B4   C4  NaN  NaN  NaN
5  NaN  NaN  NaN   A5   B5   C5
6  NaN  NaN  NaN   A6   B6   C6
7  NaN  NaN  NaN   A7   B7   C7
8  NaN  NaN  NaN   A8   B8   C8

## Merge

In [126]:
dataset1 = {
    "A": ["A1","A2","A3"],
    "B":["B1","B2","B3",],
    "Anahtar":["C1","C2","C3",],
}
dataset2 = {
    "X": ["X5","X6","X7","X8"],
    "Y":["Y5","Y6","Y7","Y8"],
    "Anahtar":["C1","C2","C7","C8"],
}

In [127]:
df1=pd.DataFrame(dataset1,index=[1,2,3])
df2=pd.DataFrame(dataset2,index=[1,2,3,4])

In [128]:
df1

A   B Anahtar
1  A1  B1      C1
2  A2  B2      C2
3  A3  B3      C3

In [129]:
df2

X   Y Anahtar
1  X5  Y5      C1
2  X6  Y6      C2
3  X7  Y7      C7
4  X8  Y8      C8

In [131]:
pd.merge(df1,df2,how="inner",on="Anahtar")

A   B Anahtar   X   Y
0  A1  B1      C1  X5  Y5
1  A2  B2      C2  X6  Y6

## Join

In [132]:
dataset1 = {
    "A": ["A1","A2","A3"],
    "B":["B1","B2","B3",],
}
dataset2 = {
    "X": ["X5","X6","X7","X8"],
    "Y":["Y5","Y6","Y7","Y8"],
}

In [133]:
df1=pd.DataFrame(dataset1,index=[1,2,3])
df2=pd.DataFrame(dataset2,index=[1,2,3,4])

In [134]:
df1.join(df2)

A   B   X   Y
1  A1  B1  X5  Y5
2  A2  B2  X6  Y6
3  A3  B3  X7  Y7

In [135]:
df2.join(df1)

X   Y    A    B
1  X5  Y5   A1   B1
2  X6  Y6   A2   B2
3  X7  Y7   A3   B3
4  X8  Y8  NaN  NaN