##### Numpy'ı Dahil Edin

In [21]:
import numpy as np

##### 5 tane 1 barındıran bir array oluşturun

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# Bu satırı çalıştırmayın

array([1., 1., 1., 1., 1.])

##### 5 tane 0 barındıran bir array oluşturun

In [23]:
b= np.zeros(5)

In [24]:
b

array([0., 0., 0., 0., 0.])

In [6]:
# Bu satırı çalıştırmayın

array([0., 0., 0., 0., 0.])

##### 2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun

In [25]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
# Bu satırı çalıştırmayın

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

##### 5 tane 10 bulunan bir array oluşturun

In [26]:
np.ones([1,5])*10

array([[10., 10., 10., 10., 10.]])

In [27]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [10]:
# Bu satırı çalıştırmayın

array([10., 10., 10., 10., 10.])

##### 1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun

In [31]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
np.arange(4,16)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# Bu satırı çalıştırmayın

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### 4x4'lük bir birim matris oluşturun

In [36]:
a= np.ones([4,4])

In [42]:
a= np.eye(4)

In [43]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Bu satırı çalıştırmayın

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### 0 ile 5 arasında rastgele değerler üretin

In [46]:
b = np.random.randint(0,5)

In [47]:
b

4

In [44]:
np.random.rand()*5

0.46217834391190427

In [48]:
b = np.random.randint(0,5,5)

In [49]:
b

array([3, 0, 4, 0, 0])

In [45]:
np.random.rand()*5

0.897030755912045

In [31]:
np.random.randint(0,5)

3

In [20]:
# Bu satırı çalıştırmayın

4.5693236808831825

##### 5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun

In [52]:
np.random.randn(25).reshape(5,5)

array([[-1.00366927, -0.43558662, -1.64061718, -0.64186659, -1.45434588],
       [ 1.44433028,  0.32954826,  0.34313554,  0.26661039, -0.39640028],
       [ 0.50929239,  3.01184825,  1.20357397,  0.55012147,  0.02727168],
       [ 0.74495527, -3.51819366, -0.97269264,  0.07028511,  0.26543372],
       [ 0.9164634 ,  0.08541029,  0.11573567,  0.4064078 ,  1.15375963]])

In [21]:
# Bu satırı çalıştırmayın

array([[-1.05647946,  0.88447651, -0.09589524,  0.707474  , -1.27075888],
       [ 1.98577112,  2.11969776, -0.62400642,  0.69932275,  0.11141592],
       [-0.71398274,  0.85916974,  0.51843923,  2.31872337,  0.48762873],
       [-1.18549889,  0.30847846,  1.0822357 ,  1.43461576, -0.10142078],
       [-0.15602908,  0.30583364,  1.69070191,  0.06727983, -0.17285088]])

##### 1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun

In [55]:
b= np.linspace(1,5,20)

In [56]:
b

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [23]:
# Bu satırı çalıştırmayın

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

### Array Indekslenmesi

In [57]:
arr  = np.arange(1,101).reshape(10,10)

In [58]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [90]:
arr[:12,3:4]

array([[ 4],
       [14],
       [24],
       [34],
       [44],
       [54],
       [64],
       [74],
       [84],
       [94]])

##### Indeks işlemlerini kullanarak aşağıdaki sonuçları elde etmeye çalışın

In [59]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [85]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [61]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [31]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [70]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [34]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [83]:
arr[:3,1]

array([ 2, 12, 22])

In [36]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 2, 12, 22])

In [84]:
arr[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [91]:
arr[:4,3:5]

array([[ 4,  5],
       [14, 15],
       [24, 25],
       [34, 35]])

In [37]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([[ 2],
       [12],
       [22]])

In [94]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [38]:
# Bu celli çalıştırmayın.Aksi Halde Doğru Outputlar silinecektir.

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### Array Operasyonları

Not: Arrayler rastgele sayılarla çalıştırıldığı için sizde çıkan sonuçlar buradakilerle aynı olmayacaktır.

In [96]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [97]:
arr1

array([[2, 2, 1],
       [2, 1, 0],
       [2, 2, 2]])

In [98]:
arr2

array([[3, 4, 3],
       [2, 2, 3],
       [0, 4, 1]])

##### İki Matrisi Toplayın

In [99]:
arr1+arr2

array([[5, 6, 4],
       [4, 3, 3],
       [2, 6, 3]])

##### İki Matrisi Çarpın

In [100]:
arr1*arr2

array([[6, 8, 3],
       [4, 2, 0],
       [0, 8, 2]])

##### arr1 matrisinin tüm elemanlarının ortalamasını bulun

In [101]:
arr1.mean()

1.5555555555555556

##### arr1 matrisinin tüm elemanlarının toplamını bulun

In [102]:
arr1.sum()

14

In [106]:
narray=np.array([1,2,3,4,5,6,7,8,9])

In [107]:
np.sin(narray)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [108]:
np.cos(narray)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [109]:
np.sqrt(narray)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [110]:
np.log(narray)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [111]:
narray.var()

6.666666666666667

In [112]:
narray.std()

2.581988897471611

In [113]:
np.median(narray)

5.0

In [114]:
narray2=np.array([9,8,7,6,5,4,3,2,1])

In [116]:
np.add(narray,narray2)

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [118]:
np.subtract(narray,narray2)

array([-8, -6, -4, -2,  0,  2,  4,  6,  8])

In [119]:
np.multiply(narray,narray2)

array([ 9, 16, 21, 24, 25, 24, 21, 16,  9])

In [120]:
np.divide(narray,narray2)

array([0.11111111, 0.25      , 0.42857143, 0.66666667, 1.        ,
       1.5       , 2.33333333, 4.        , 9.        ])

In [139]:
np.random.randn(1,100,25)

array([[[-0.96979421,  0.98619608, -1.08079539, ...,  0.20335524,
          0.95036187, -0.31227477],
        [ 3.35041664, -1.46411302,  0.88377656, ...,  0.24899513,
         -0.11489199,  0.72231933],
        [ 0.54772951,  0.39632308,  0.39146523, ..., -1.31938239,
          0.64476631, -0.36919936],
        ...,
        [-0.22931627,  0.25562145, -0.1579114 , ...,  1.16246922,
          0.03613865, -0.07474751],
        [ 0.97773739, -0.00955837,  2.06494143, ..., -0.15222985,
         -0.81889666, -0.28701043],
        [-0.65835542,  0.24331057,  1.5105709 , ..., -0.76207579,
          1.48831635,  0.7107951 ]]])

In [140]:
np.random.randint(1,100,25)

array([96,  5, 31, 84, 77, 11, 33, 31, 22, 51, 68, 27, 28, 12, 31, 84, 37,
       51, 32, 32, 18, 91, 52, 46, 38])